In [53]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
#Ejemplos de matrices documento-palabra y su significado

x=np.linspace(0,3, 10)
print (x)


[ 0.          0.33333333  0.66666667  1.          1.33333333  1.66666667
  2.          2.33333333  2.66666667  3.        ]


(10,)

In [54]:
A=np.matrix('1 2 3 0 0;0 0 0 1 1;1 0 1 0 0; 0 0 0 2 1')

In [5]:
A

matrix([[1, 2, 3, 0, 0],
        [0, 0, 0, 1, 1],
        [1, 0, 1, 0, 0],
        [0, 0, 0, 2, 1]])

In [71]:
U,S,V=np.linalg.svd(A, full_matrices=True)

In [72]:
U

matrix([[ 0.95709203,  0.        , -0.28978415,  0.        ],
        [ 0.        , -0.52573111,  0.        ,  0.85065081],
        [ 0.28978415,  0.        ,  0.95709203,  0.        ],
        [-0.        , -0.85065081, -0.        , -0.52573111]])

In [73]:
V

matrix([[  3.19700253e-01,   4.90798636e-01,   8.10498888e-01,
           0.00000000e+00,   0.00000000e+00],
        [ -6.40987562e-17,  -6.40987562e-17,   6.40987562e-17,
          -8.50650808e-01,  -5.25731112e-01],
        [  7.51304476e-01,  -6.52520778e-01,   9.87836974e-02,
           0.00000000e+00,   0.00000000e+00],
        [ -3.20493781e-16,  -3.20493781e-16,   3.20493781e-16,
          -5.25731112e-01,   8.50650808e-01],
        [  5.77350269e-01,   5.77350269e-01,  -5.77350269e-01,
          -2.54562284e-16,   5.22593833e-16]])

In [109]:
def ndprint(a, format_string ='{0:.2f}'):
    for i, v in enumerate(a):
        print [format_string.format(v,i)]


In [75]:
V.H

matrix([[  3.19700253e-01,  -6.40987562e-17,   7.51304476e-01,
          -3.20493781e-16,   5.77350269e-01],
        [  4.90798636e-01,  -6.40987562e-17,  -6.52520778e-01,
          -3.20493781e-16,   5.77350269e-01],
        [  8.10498888e-01,   6.40987562e-17,   9.87836974e-02,
           3.20493781e-16,  -5.77350269e-01],
        [  0.00000000e+00,  -8.50650808e-01,   0.00000000e+00,
          -5.25731112e-01,  -2.54562284e-16],
        [  0.00000000e+00,  -5.25731112e-01,   0.00000000e+00,
           8.50650808e-01,   5.22593833e-16]])

In [76]:
print (V.H)

[[  3.19700253e-01  -6.40987562e-17   7.51304476e-01  -3.20493781e-16
    5.77350269e-01]
 [  4.90798636e-01  -6.40987562e-17  -6.52520778e-01  -3.20493781e-16
    5.77350269e-01]
 [  8.10498888e-01   6.40987562e-17   9.87836974e-02   3.20493781e-16
   -5.77350269e-01]
 [  0.00000000e+00  -8.50650808e-01   0.00000000e+00  -5.25731112e-01
   -2.54562284e-16]
 [  0.00000000e+00  -5.25731112e-01   0.00000000e+00   8.50650808e-01
    5.22593833e-16]]


In [95]:
np.multiply(V.H, abs(V.H)>0.00001)

matrix([[ 0.31970025, -0.        ,  0.75130448, -0.        ,  0.57735027],
        [ 0.49079864, -0.        , -0.65252078, -0.        ,  0.57735027],
        [ 0.81049889,  0.        ,  0.0987837 ,  0.        , -0.57735027],
        [ 0.        , -0.85065081,  0.        , -0.52573111, -0.        ],
        [ 0.        , -0.52573111,  0.        ,  0.85065081,  0.        ]])

In [79]:
S

array([ 3.90014135,  2.61803399,  0.88819899,  0.38196601])

In [89]:
Sm=np.diag(S)
Sm=np.c_[Sm,np.zeros((4,1))]
print(Sm)

[[ 3.90014135  0.          0.          0.          0.        ]
 [ 0.          2.61803399  0.          0.          0.        ]
 [ 0.          0.          0.88819899  0.          0.        ]
 [ 0.          0.          0.          0.38196601  0.        ]]


In [96]:
Ar=U[:,0:1]*Sm[0:1,0:1]*V[0:1,:]
Ar=np.multiply(Ar,Ar>0.00001)

In [98]:
Ar

matrix([[ 1.19337525,  1.83205029,  3.02542554,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.36132495,  0.5547002 ,  0.91602515,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [111]:
x=V.getA()
print (x)
print (np.array_str(x, precision=2, suppress_small=True))

[[  3.19700253e-01   4.90798636e-01   8.10498888e-01   0.00000000e+00
    0.00000000e+00]
 [ -6.40987562e-17  -6.40987562e-17   6.40987562e-17  -8.50650808e-01
   -5.25731112e-01]
 [  7.51304476e-01  -6.52520778e-01   9.87836974e-02   0.00000000e+00
    0.00000000e+00]
 [ -3.20493781e-16  -3.20493781e-16   3.20493781e-16  -5.25731112e-01
    8.50650808e-01]
 [  5.77350269e-01   5.77350269e-01  -5.77350269e-01  -2.54562284e-16
    5.22593833e-16]]
[[ 0.32  0.49  0.81  0.    0.  ]
 [-0.   -0.    0.   -0.85 -0.53]
 [ 0.75 -0.65  0.1   0.    0.  ]
 [-0.   -0.    0.   -0.53  0.85]
 [ 0.58  0.58 -0.58 -0.    0.  ]]


In [67]:
V.shape


(4, 5)

In [69]:
V.H

matrix([[  3.19700253e-01,  -6.40987562e-17,   7.51304476e-01,
          -3.20493781e-16],
        [  4.90798636e-01,  -6.40987562e-17,  -6.52520778e-01,
          -3.20493781e-16],
        [  8.10498888e-01,   6.40987562e-17,   9.87836974e-02,
           3.20493781e-16],
        [  0.00000000e+00,  -8.50650808e-01,   0.00000000e+00,
          -5.25731112e-01],
        [  0.00000000e+00,  -5.25731112e-01,   0.00000000e+00,
           8.50650808e-01]])